patch jenkinsfile.cd

diff --git a/Jenkinsfile.cd b/Jenkinsfile.cd
--- a/Jenkinsfile.cd
+++ b/Jenkinsfile.cd
@@ -33,7 +33,7 @@ pipeline {
 
     parameters {
         string(
-            name: 'personal-site-59.tar.gz',
+            name: 'ARTIFACT_NAME',
             defaultValue: '',
             description: 'MinIO artifact name, for example personal-site-57.tar.gz',
             trim: true
@@ -84,11 +84,14 @@ pipeline {
                     set -eu
 
                     . deployment/CONFIG
+                    SELECTED_ARTIFACT="${ARTIFACT_NAME:-}"
 
-                    printf '%s\n' "$ARTIFACT_NAME" \
+                    printf '%s\n' "$SELECTED_ARTIFACT" \
                         | grep -Eq "^${ARTIFACT_PREFIX}-[0-9]+\\.tar\\.gz$" \
                         || {
-                            echo "Invalid artifact name: $ARTIFACT_NAME" >&2
+                            echo 'ARTIFACT_NAME is required.' >&2
+                            echo "Expected format: ${ARTIFACT_PREFIX}-<BUILD_NUMBER>.tar.gz" >&2
+                            echo 'Run this job using Build with Parameters.' >&2
                             exit 1
                         }
                 '''
